// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Implementation hints or other developer-facing comments on this node. These
 * should be omitted when representing an object for gameplay.
 */
public class Documentation {
    @JsonValue
    private String value;

    public Documentation() {
    }

    @JsonCreator
    public Documentation(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
