// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum RuleType {
    @JsonProperty("condition_meter")
    CONDITION_METER,

    @JsonProperty("impact")
    IMPACT,

    @JsonProperty("special_track")
    SPECIAL_TRACK,

    @JsonProperty("stat")
    STAT,
}
