// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A JSON schema representing a single value that's possible to represent in
 * common programming languages.
 */
public class SafeSchema {
    @JsonValue
    private Object value;

    public SafeSchema() {
    }

    @JsonCreator
    public SafeSchema(Object value) {
        this.value = value;
    }

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }
}
