// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Describes a standard player character stat.
 */
@JsonSerialize
public class StatRule {
    @JsonProperty("description")
    private MarkdownString description;

    @JsonProperty("label")
    private Label label;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("tags")
    private Tags tags;

    public StatRule() {
    }

    /**
     * Getter for description.<p>
     * A description of this stat.
     */
    public MarkdownString getDescription() {
        return description;
    }

    /**
     * Setter for description.<p>
     * A description of this stat.
     */
    public void setDescription(MarkdownString description) {
        this.description = description;
    }

    /**
     * Getter for label.<p>
     * A label for this stat.
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     * A label for this stat.
     */
    public void setLabel(Label label) {
        this.label = label;
    }

    /**
     * Getter for tags.<p>
     */
    public Tags getTags() {
        return tags;
    }

    /**
     * Setter for tags.<p>
     */
    public void setTags(Tags tags) {
        this.tags = tags;
    }
}
