// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class TagRule {
    @JsonProperty("$schema")
    private TagSchema schema;

    @JsonProperty("node_types")
    private List<TaggableNodeType> nodeTypes;

    public TagRule() {
    }

    /**
     * Getter for schema.<p>
     * The JSON schema for this tag value.
     */
    public TagSchema getSchema() {
        return schema;
    }

    /**
     * Setter for schema.<p>
     * The JSON schema for this tag value.
     */
    public void setSchema(TagSchema schema) {
        this.schema = schema;
    }

    /**
     * Getter for nodeTypes.<p>
     */
    public List<TaggableNodeType> getNodeTypes() {
        return nodeTypes;
    }

    /**
     * Setter for nodeTypes.<p>
     */
    public void setNodeTypes(List<TaggableNodeType> nodeTypes) {
        this.nodeTypes = nodeTypes;
    }
}
