// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class TagRule {
    @JsonProperty("$schema")
    private TagSchema schema;

    @JsonProperty("applies_to")
    private List<TaggableNodeType> appliesTo;

    public TagRule() {
    }

    /**
     * Getter for schema.<p>
     */
    public TagSchema getSchema() {
        return schema;
    }

    /**
     * Setter for schema.<p>
     */
    public void setSchema(TagSchema schema) {
        this.schema = schema;
    }

    /**
     * Getter for appliesTo.<p>
     */
    public List<TaggableNodeType> getAppliesTo() {
        return appliesTo;
    }

    /**
     * Setter for appliesTo.<p>
     */
    public void setAppliesTo(List<TaggableNodeType> appliesTo) {
        this.appliesTo = appliesTo;
    }
}
