// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A JSON schema used to validate the tag data.
 */
public class TagSchema {
    @JsonValue
    private Object value;

    public TagSchema() {
    }

    @JsonCreator
    public TagSchema(Object value) {
        this.value = value;
    }

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }
}
