// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(RuleTypeJsonConverter))]
    public enum RuleType
    {
        ConditionMeter,

        Impact,

        SpecialTrack,

        Stat,
    }
    public class RuleTypeJsonConverter : JsonConverter<RuleType>
    {
        public override RuleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "condition_meter":
                    return RuleType.ConditionMeter;
                case "impact":
                    return RuleType.Impact;
                case "special_track":
                    return RuleType.SpecialTrack;
                case "stat":
                    return RuleType.Stat;
                default:
                    throw new ArgumentException(String.Format("Bad RuleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, RuleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case RuleType.ConditionMeter:
                    JsonSerializer.Serialize<string>(writer, "condition_meter", options);
                    return;
                case RuleType.Impact:
                    JsonSerializer.Serialize<string>(writer, "impact", options);
                    return;
                case RuleType.SpecialTrack:
                    JsonSerializer.Serialize<string>(writer, "special_track", options);
                    return;
                case RuleType.Stat:
                    JsonSerializer.Serialize<string>(writer, "stat", options);
                    return;
            }
        }
    }
}
