// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A JSON schema representing a single value (or reference) that's possible
    /// to represent in most languages.
    /// </summary>
    [JsonConverter(typeof(SafeValueSchemaJsonConverter))]
    public class SafeValueSchema
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public object Value { get; set; }
    }

    public class SafeValueSchemaJsonConverter : JsonConverter<SafeValueSchema>
    {
        public override SafeValueSchema Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new SafeValueSchema { Value = JsonSerializer.Deserialize<object>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, SafeValueSchema value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<object>(writer, value.Value, options);
        }
    }
}
