// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    public class TagRule
    {
        [JsonPropertyName("$schema")]
        public TagSchema Schema { get; set; }

        [JsonPropertyName("applies_to")]
        public IList<TaggableNodeType> AppliesTo { get; set; }
    }
}
