// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    public class TagRule
    {
        /// <summary>
        /// The JSON schema for this tag value.
        /// </summary>
        [JsonPropertyName("$schema")]
        public TagSchema Schema { get; set; }

        [JsonPropertyName("node_types")]
        public IList<TaggableNodeType> NodeTypes { get; set; }
    }
}
