// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// JSON schema used to validate the tag data, with a mandatory description.
    /// Only a subset of all possible JSON schema are allowed, including
    /// references to some Datasworn types.
    /// </summary>
    [JsonConverter(typeof(TagSchemaJsonConverter))]
    public class TagSchema
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public object Value { get; set; }
    }

    public class TagSchemaJsonConverter : JsonConverter<TagSchema>
    {
        public override TagSchema Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new TagSchema { Value = JsonSerializer.Deserialize<object>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, TagSchema value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<object>(writer, value.Value, options);
        }
    }
}
